FROM python:3.11-slim
LABEL org.opencontainers.image.source=https://github.com/brain-bbqs/reproforce
LABEL org.opencontainers.image.description="A Docker image of the code environment used by the figure generation of the Seeber-Suthana-2024 project."

RUN pip install --no-cache-dir matplotlib pynwb
